# Generated by Django 4.1.9 on 2023-06-26 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="user.user",
            ),
        ),
    ]
